
include:
    - .docker/compose-db.yml


services:

    ##########
    # APACHE #
    ##########

    symfony:
        container_name: symfony_php
        # docker build -f ".docker/symfony/php.Dockerfile" --pull -t fs-php:latest ".docker"
        image: fs-php:latest
        # build:
        #     context: .docker
        #     dockerfile: php.Dockerfile
        restart: always
        user: 1000:1000
        ports: 
            - 8001:81   # symfony server
            - 8080:8080 # npm dev server (must match weback config)
        command: sleep infinity
        volumes:
            - ./apps/symfony:/var/www/application
            # - .docker/symfony/server/apache2/000-default.conf:/etc/apache2/sites-enabled/000-default.conf:ro
            - .docker/symfony/server/php/conf.d/php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini:ro
            # - .docker/server/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
        profiles:
          - symfony

    ########
    # NODE #
    ########

    react:
        image: node:24
        container_name: react_node
        restart: always
        user: 1000:1000
        working_dir: /var/www/application
        volumes:
            - ./apps/vite-react:/var/www/application
        command: sleep infinity
        ports:
            - 5171:5173 # npm dev server
        profiles:
          - react

    vue:
        image: node:24
        container_name: vue_node
        restart: always
        user: 1000:1000
        working_dir: /var/www/application
        volumes:
            - ./apps/vite-vue:/var/www/application
        command: sleep infinity
        ports:
            - 5172:5173 # npm dev server
        profiles:
          - vue

    ### TRAEFIK
    # @https://doc.traefik.io/traefik/getting-started/quick-start
    # @http://localhost:8080/api/rawdata
    # traefik:
    #     container_name: traefik
    #     # The official v2.8 Traefik docker image
    #     image: traefik:v2.7
    #     # Enables the web UI and tells Traefik to listen to docker
    #     command:
    #         --api.insecure=true
    #         --providers.docker
    #     #      --entrypoints.websecure.address=:443
    #     # ports:
    #     #     # The HTTP port
    #     #     - "80:80"
    #     #     # The Web UI (enabled by --api.insecure=true)
    #     #     - "8080:8080"
    #     volumes:
    #         # So that Traefik can listen to the Docker events
    #         - /var/run/docker.sock:/var/run/docker.sock
    #         # -> on services
    #     labels:
    #         - "traefik.http.routers.front.rule=Host(`front`)"

######################
# Other useful boxes #
# https://devilbox.org
# https://easyphp.org
# https://laradock.io
# https://laragon.org
# https://github.com/laraedit/laraedit-docker
# https://hub.docker.com/r/mattrayner/lamp
######################
