
networks:
    default:
        name: fs-ai-network
        driver: bridge

services:

    #######
    # AI #
    #######
    
    ai-node:
        container_name: fs-ai-node
        image: node:latest
        restart: always   
    #     user: 1000:1000
    #     environment:
    #         API_DSN: ''
        volumes:
            - ./ai:/var/www/application
        ports:
            - 5111:5173 # ai-node dev server
        working_dir: /var/www/application
        command: sleep infinity
        profiles:
            - ai

    mcp-filesystem:
        container_name: fs-ai-mcpfilesystem
        image: mcp/filesystem:latest
        restart: always
        volumes:
            - ./ai/data:/data
        command: sleep infinity
        profiles:
            - ai
