
networks:
    default:
        name: fs-ai-network
        driver: bridge

services:

    #######
    # AI #
    #######

    ai-node:
        # image: node:latest
        container_name: fs-ai-node
        build:
            context: .
            dockerfile: .docker/node/node.Dockerfile
        user: 1000:1000
    #     environment:
    #         API_DSN: ''
        volumes:
            - ./ai:/var/www/application
        ports:
            - 5111:5173
            - 5112:3000
        working_dir: /var/www/application
        command: sleep infinity
        profiles:
            - ai

    # @doc https://github.com/njbrake/filesystem-mcp-server
    local-mcp-filesystem:
        image: ghcr.io/njbrake/filesystem-mcp-server:main
        container_name: fs-ai-mcpfilesystem
        ports: [8123:8123]
        volumes:
            - ./ai/data:/data
        profiles:
            - ai


    # https://hub.docker.com/categories/machine-learning-and-ai
    # https://hub.docker.com/r/mcp/filesystem

    # NO NEED:
    # Direclty spawned by Claude Desktop

    # mcp-filesystem:
    #     image: mcp/filesystem:latest
    #     volumes:
    #         - ./ai/data:/data
    #     command: ["/data"]
    #     stdin_open: true
    #     tty: true
