#!/bin/bash

if [[
    "$1" == "ai" ||
    "$1" == "git"
]]; then
    # all args except first ${parameter:offset:length}
    ./scripts/run/"$1".sh ${@:2}
    exit 0
fi

echo "Error: Run command '$1' not found!"
exit 1
