# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration

#############
# SNC REDIS #
# @https://github.com/snc/sncredisbundle
#############

parameters:
    # @TODO use "app.redis.enabled" parameters
    # use_redis: ~ # ~|local|remote

services:
    # _default configuration for services in !this! file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    #####################
    # _instanceof is like _default : it only works for services declared in CURRENT .yaml file !
    #####################

    App\MainBundle\Manager\Data\RedisManager:
        arguments:
            $redisClient: '@snc_redis.default' # @see snc_redis.yaml