
networks:
    default:
        name: fs-ai-network
        driver: bridge

services:

    ######
    # AI #
    ######

    app:
        container_name: fs-ai-app
        image: fs-php:latest
        restart: always
        user: 1000:1000
        environment:
            MYSQL_DSN: ''
            REDIS_DSN: ''
        ports:
            - 8151:81   # symfony server
        command: sleep infinity
        volumes:
            - .:/var/www/application
        profiles:
          - ai

    node:
        container_name: fs-ai-node
        image: node:latest
        restart: always
        profiles:
          - ai

    mcp-filesystem:
        image: mcp/filesystem:latest
        restart: always
        profiles:
          - ai
