
# volumes:
#     mysql:

networks:
    default:
        name: fs-network
        driver: bridge

services:

    ################
    ### DATABASE ###
    ################

    ### MYSQL ###

    # https://hub.docker.com/_/mysql
    mysql:
        image: mysql:9.7
        container_name: fs-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            MYSQL_DATABASE: mydb
            MYSQL_TCP_PORT: 3306 # Mandatory 3306 for Adminer
        volumes:
            - ./init/mysql/:/docker-entrypoint-initdb.d/:ro
            # - ./data/mysql/my.cnf:/etc/mysql/my.cnf:ro
            # - ./data/mysql/conf.d/my-custom.cnf:/etc/mysql/conf.d/my-custom.cnf:ro
            # - mysql:/var/lib/mysql
        ports: [8801:3306]
        profiles:
          - db

    # https://hub.docker.com/_/adminer
    adminer:
        image: adminer:5-standalone
        container_name: fs-adminer
        restart: always
        ports: [8881:8080]
        profiles:
          - db

    # phpmyadmin:
    #     image: phpmyadmin:5.0
    #     restart: always
    #     ports:
    #         - 8081:80
    #     environment:
    #         - PMA_ARBITRARY=1
    #     external_links:
    #         - mysql:mysql

