
# volumes:
#     mysql:

# services:

    ################
    ### DATABASE ###
    ################

    ### MYSQL ###

    # mysql:
    #     image: mysql:5.7
    #     restart: always
    #     environment:
    #         MYSQL_ROOT_PASSWORD: root
    #         MYSQL_USER: user
    #         MYSQL_PASSWORD: pass
    #         MYSQL_DATABASE: mydb
    #         MYSQL_TCP_PORT: 3306 # Mandatory 3306 for Adminer
    #     volumes:
    #         - ./data/mysql/my.cnf:/etc/mysql/my.cnf:ro
    #         - ./data/mysql/conf.d/my-custom.cnf:/etc/mysql/conf.d/my-custom.cnf:ro
    #         - mysql:/var/lib/mysql

    # adminer:
    #     image: adminer:4-standalone
    #     restart: always
    #     ports: [8081:8080]

    # phpmyadmin:
    #     image: phpmyadmin:5.0
    #     restart: always
    #     ports:
    #         - 8081:80
    #     environment:
    #         - PMA_ARBITRARY=1
    #     external_links:
    #         - mysql:mysql
    #     networks:
    #         - sym
