# @https://github.com/snc/SncRedisBundle/tree/master/docs

when@dev:
    snc_redis:
        # Define your clients here. The example below connects to database 0 of the default Redis server.
        # See https://github.com/snc/SncRedisBundle/blob/master/docs/README.md for instructions on
        # how to configure the bundle.
        clients:
            default:
                #alias: local
                type: predis
                dsn: "redis://redis:6379/0"
                logging: '%kernel.debug%'

when@test:
    snc_redis:
        clients:
            default:
                type: predis
                dsn: "redis://redis:6379/1"

            #  # @snc_redis.elasticache
            # elasticache:
            #     type: predis
            #     alias: elasticache
            #     dsn: "%env(AWS_TERMINAISON)%"
            #     logging: '%kernel.debug%'

###
# NO snc_redis PROD BUNDLE !
###
